# Generated by Django 3.2.12 on 2022-12-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, verbose_name='section')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='countryname',
        ),
    ]
